CREATE TABLE [dbo].[DVIRPower](
	[DVIRPowerId] [int] IDENTITY(1,1) NOT NULL,
	[DriverNo] [int] NULL,
	[TractorId] [varchar](11) NULL,
	[Location] [varchar](20) NULL,
	[Mileage] [varchar](10) NULL,
	[NoDefects] [bit] NULL,
	[CabDoorsWindows] [bit] NULL,
	[BodyDoors] [bit] NULL,
	[OilLeak] [bit] NULL,
	[GreaseLeak] [bit] NULL,
	[CoolantLeak] [bit] NULL,
	[FuelLeak] [bit] NULL,
	[OtherGeneral] [varchar](20) NULL,
	[GeneralRemark] [varchar](40) NULL,
	[OilLevel] [bit] NULL,
	[CoolantLevel] [bit] NULL,
	[Belts] [bit] NULL,
	[OtherEngine] [varchar](20) NULL,
	[EngineRemark] [varchar](40) NULL,
	[GaugesWarning] [bit] NULL,
	[WindshieldWipers] [bit] NULL,
	[Horns] [bit] NULL,
	[HeaterDefroster] [bit] NULL,
	[Mirrors] [bit] NULL,
	[Steering] [bit] NULL,
	[Clutch] [bit] NULL,
	[ServiceBrakes] [bit] NULL,
	[ParkingBrake] [bit] NULL,
	[EmergencyBrake] [bit] NULL,
	[Triangles] [bit] NULL,
	[FireExtinguisher] [bit] NULL,
	[OtherSafetyEquipment] [bit] NULL,
	[SpareFuses] [bit] NULL,
	[SeatBelts] [bit] NULL,
	[OtherInCab] [varchar](20) NULL,
	[InCabRemark] [varchar](40) NULL,
	[Lights] [bit] NULL,
	[Reflectors] [bit] NULL,
	[Suspension] [bit] NULL,
	[Tires] [bit] NULL,
	[WheelsRimsLugs] [bit] NULL,
	[Battery] [bit] NULL,
	[Exhaust] [bit] NULL,
	[Brakes] [bit] NULL,
	[AirLines] [bit] NULL,
	[FifthWheel] [bit] NULL,
	[OtherCoupling] [bit] NULL,
	[TieDowns] [bit] NULL,
	[OtherExterior] [varchar](20) NULL,
	[ExteriorRemark] [varchar](40) NULL,
	[CreatedDateTime] [datetime] NULL,
	[CertifyRepairsDate] [datetime] NULL,
	[RepairsMadeFlag] [bit] NULL,
	[RONumber] [varchar](20) NULL,
	[CertifiedBy] [varchar](30) NULL,
	[CertifiedLocation] [varchar](30) NULL,
	[ReviewingDriverDate] [datetime] NULL,
	[ReviewingDriverName] [varchar](30) NULL,
	[ReviewingDriverNumber] [varchar](10) NULL,
 CONSTRAINT [PK_DVIRPower] PRIMARY KEY CLUSTERED 
(
	[DVIRPowerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


