#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailDelivery.Core.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DVIR")]
	public partial class DVIRDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDVIRPower(DVIRPower instance);
    partial void UpdateDVIRPower(DVIRPower instance);
    partial void DeleteDVIRPower(DVIRPower instance);
    partial void InsertDVIRTowed(DVIRTowed instance);
    partial void UpdateDVIRTowed(DVIRTowed instance);
    partial void DeleteDVIRTowed(DVIRTowed instance);
    #endregion
		
		public DVIRDataContext() : 
				base(global::RailDelivery.Core.Properties.Settings.Default.DVIRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DVIRDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DVIRDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DVIRDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DVIRDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DVIRPower> DVIRPowers
		{
			get
			{
				return this.GetTable<DVIRPower>();
			}
		}
		
		public System.Data.Linq.Table<DVIRTowed> DVIRToweds
		{
			get
			{
				return this.GetTable<DVIRTowed>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVIRPower")]
	public partial class DVIRPower : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DVIRPowerId;
		
		private System.Nullable<int> _DriverNo;
		
		private string _TractorId;
		
		private string _Location;
		
		private string _Mileage;
		
		private System.Nullable<bool> _NoDefects;
		
		private System.Nullable<bool> _CabDoorsWindows;
		
		private System.Nullable<bool> _BodyDoors;
		
		private System.Nullable<bool> _OilLeak;
		
		private System.Nullable<bool> _GreaseLeak;
		
		private System.Nullable<bool> _CoolantLeak;
		
		private System.Nullable<bool> _FuelLeak;
		
		private string _OtherGeneral;
		
		private string _GeneralRemark;
		
		private System.Nullable<bool> _OilLevel;
		
		private System.Nullable<bool> _CoolantLevel;
		
		private System.Nullable<bool> _Belts;
		
		private string _OtherEngine;
		
		private string _EngineRemark;
		
		private System.Nullable<bool> _GaugesWarning;
		
		private System.Nullable<bool> _WindshieldWipers;
		
		private System.Nullable<bool> _Horns;
		
		private System.Nullable<bool> _HeaterDefroster;
		
		private System.Nullable<bool> _Mirrors;
		
		private System.Nullable<bool> _Steering;
		
		private System.Nullable<bool> _Clutch;
		
		private System.Nullable<bool> _ServiceBrakes;
		
		private System.Nullable<bool> _ParkingBrake;
		
		private System.Nullable<bool> _EmergencyBrake;
		
		private System.Nullable<bool> _Triangles;
		
		private System.Nullable<bool> _FireExtinguisher;
		
		private System.Nullable<bool> _OtherSafetyEquipment;
		
		private System.Nullable<bool> _SpareFuses;
		
		private System.Nullable<bool> _SeatBelts;
		
		private string _OtherInCab;
		
		private string _InCabRemark;
		
		private System.Nullable<bool> _Lights;
		
		private System.Nullable<bool> _Reflectors;
		
		private System.Nullable<bool> _Suspension;
		
		private System.Nullable<bool> _Tires;
		
		private System.Nullable<bool> _WheelsRimsLugs;
		
		private System.Nullable<bool> _Battery;
		
		private System.Nullable<bool> _Exhaust;
		
		private System.Nullable<bool> _Brakes;
		
		private System.Nullable<bool> _AirLines;
		
		private System.Nullable<bool> _FifthWheel;
		
		private System.Nullable<bool> _OtherCoupling;
		
		private System.Nullable<bool> _TieDowns;
		
		private string _OtherExterior;
		
		private string _ExteriorRemark;
		
		private System.Nullable<System.DateTime> _CreatedDateTime;
		
		private System.Nullable<System.DateTime> _CertifyRepairsDate;
		
		private System.Nullable<bool> _RepairsMadeFlag;
		
		private string _RONumber;
		
		private string _CertifiedBy;
		
		private string _CertifiedLocation;
		
		private System.Nullable<System.DateTime> _ReviewingDriverDate;
		
		private string _ReviewingDriverName;
		
		private string _ReviewingDriverNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDVIRPowerIdChanging(int value);
    partial void OnDVIRPowerIdChanged();
    partial void OnDriverNoChanging(System.Nullable<int> value);
    partial void OnDriverNoChanged();
    partial void OnTractorIdChanging(string value);
    partial void OnTractorIdChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnMileageChanging(string value);
    partial void OnMileageChanged();
    partial void OnNoDefectsChanging(System.Nullable<bool> value);
    partial void OnNoDefectsChanged();
    partial void OnCabDoorsWindowsChanging(System.Nullable<bool> value);
    partial void OnCabDoorsWindowsChanged();
    partial void OnBodyDoorsChanging(System.Nullable<bool> value);
    partial void OnBodyDoorsChanged();
    partial void OnOilLeakChanging(System.Nullable<bool> value);
    partial void OnOilLeakChanged();
    partial void OnGreaseLeakChanging(System.Nullable<bool> value);
    partial void OnGreaseLeakChanged();
    partial void OnCoolantLeakChanging(System.Nullable<bool> value);
    partial void OnCoolantLeakChanged();
    partial void OnFuelLeakChanging(System.Nullable<bool> value);
    partial void OnFuelLeakChanged();
    partial void OnOtherGeneralChanging(string value);
    partial void OnOtherGeneralChanged();
    partial void OnGeneralRemarkChanging(string value);
    partial void OnGeneralRemarkChanged();
    partial void OnOilLevelChanging(System.Nullable<bool> value);
    partial void OnOilLevelChanged();
    partial void OnCoolantLevelChanging(System.Nullable<bool> value);
    partial void OnCoolantLevelChanged();
    partial void OnBeltsChanging(System.Nullable<bool> value);
    partial void OnBeltsChanged();
    partial void OnOtherEngineChanging(string value);
    partial void OnOtherEngineChanged();
    partial void OnEngineRemarkChanging(string value);
    partial void OnEngineRemarkChanged();
    partial void OnGaugesWarningChanging(System.Nullable<bool> value);
    partial void OnGaugesWarningChanged();
    partial void OnWindshieldWipersChanging(System.Nullable<bool> value);
    partial void OnWindshieldWipersChanged();
    partial void OnHornsChanging(System.Nullable<bool> value);
    partial void OnHornsChanged();
    partial void OnHeaterDefrosterChanging(System.Nullable<bool> value);
    partial void OnHeaterDefrosterChanged();
    partial void OnMirrorsChanging(System.Nullable<bool> value);
    partial void OnMirrorsChanged();
    partial void OnSteeringChanging(System.Nullable<bool> value);
    partial void OnSteeringChanged();
    partial void OnClutchChanging(System.Nullable<bool> value);
    partial void OnClutchChanged();
    partial void OnServiceBrakesChanging(System.Nullable<bool> value);
    partial void OnServiceBrakesChanged();
    partial void OnParkingBrakeChanging(System.Nullable<bool> value);
    partial void OnParkingBrakeChanged();
    partial void OnEmergencyBrakeChanging(System.Nullable<bool> value);
    partial void OnEmergencyBrakeChanged();
    partial void OnTrianglesChanging(System.Nullable<bool> value);
    partial void OnTrianglesChanged();
    partial void OnFireExtinguisherChanging(System.Nullable<bool> value);
    partial void OnFireExtinguisherChanged();
    partial void OnOtherSafetyEquipmentChanging(System.Nullable<bool> value);
    partial void OnOtherSafetyEquipmentChanged();
    partial void OnSpareFusesChanging(System.Nullable<bool> value);
    partial void OnSpareFusesChanged();
    partial void OnSeatBeltsChanging(System.Nullable<bool> value);
    partial void OnSeatBeltsChanged();
    partial void OnOtherInCabChanging(string value);
    partial void OnOtherInCabChanged();
    partial void OnInCabRemarkChanging(string value);
    partial void OnInCabRemarkChanged();
    partial void OnLightsChanging(System.Nullable<bool> value);
    partial void OnLightsChanged();
    partial void OnReflectorsChanging(System.Nullable<bool> value);
    partial void OnReflectorsChanged();
    partial void OnSuspensionChanging(System.Nullable<bool> value);
    partial void OnSuspensionChanged();
    partial void OnTiresChanging(System.Nullable<bool> value);
    partial void OnTiresChanged();
    partial void OnWheelsRimsLugsChanging(System.Nullable<bool> value);
    partial void OnWheelsRimsLugsChanged();
    partial void OnBatteryChanging(System.Nullable<bool> value);
    partial void OnBatteryChanged();
    partial void OnExhaustChanging(System.Nullable<bool> value);
    partial void OnExhaustChanged();
    partial void OnBrakesChanging(System.Nullable<bool> value);
    partial void OnBrakesChanged();
    partial void OnAirLinesChanging(System.Nullable<bool> value);
    partial void OnAirLinesChanged();
    partial void OnFifthWheelChanging(System.Nullable<bool> value);
    partial void OnFifthWheelChanged();
    partial void OnOtherCouplingChanging(System.Nullable<bool> value);
    partial void OnOtherCouplingChanged();
    partial void OnTieDownsChanging(System.Nullable<bool> value);
    partial void OnTieDownsChanged();
    partial void OnOtherExteriorChanging(string value);
    partial void OnOtherExteriorChanged();
    partial void OnExteriorRemarkChanging(string value);
    partial void OnExteriorRemarkChanged();
    partial void OnCreatedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateTimeChanged();
    partial void OnCertifyRepairsDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCertifyRepairsDateChanged();
    partial void OnRepairsMadeFlagChanging(System.Nullable<bool> value);
    partial void OnRepairsMadeFlagChanged();
    partial void OnRONumberChanging(string value);
    partial void OnRONumberChanged();
    partial void OnCertifiedByChanging(string value);
    partial void OnCertifiedByChanged();
    partial void OnCertifiedLocationChanging(string value);
    partial void OnCertifiedLocationChanged();
    partial void OnReviewingDriverDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReviewingDriverDateChanged();
    partial void OnReviewingDriverNameChanging(string value);
    partial void OnReviewingDriverNameChanged();
    partial void OnReviewingDriverNumberChanging(string value);
    partial void OnReviewingDriverNumberChanged();
    #endregion
		
		public DVIRPower()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVIRPowerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DVIRPowerId
		{
			get
			{
				return this._DVIRPowerId;
			}
			set
			{
				if ((this._DVIRPowerId != value))
				{
					this.OnDVIRPowerIdChanging(value);
					this.SendPropertyChanging();
					this._DVIRPowerId = value;
					this.SendPropertyChanged("DVIRPowerId");
					this.OnDVIRPowerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverNo", DbType="Int")]
		public System.Nullable<int> DriverNo
		{
			get
			{
				return this._DriverNo;
			}
			set
			{
				if ((this._DriverNo != value))
				{
					this.OnDriverNoChanging(value);
					this.SendPropertyChanging();
					this._DriverNo = value;
					this.SendPropertyChanged("DriverNo");
					this.OnDriverNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TractorId", DbType="VarChar(11)")]
		public string TractorId
		{
			get
			{
				return this._TractorId;
			}
			set
			{
				if ((this._TractorId != value))
				{
					this.OnTractorIdChanging(value);
					this.SendPropertyChanging();
					this._TractorId = value;
					this.SendPropertyChanged("TractorId");
					this.OnTractorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(20)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mileage", DbType="VarChar(10)")]
		public string Mileage
		{
			get
			{
				return this._Mileage;
			}
			set
			{
				if ((this._Mileage != value))
				{
					this.OnMileageChanging(value);
					this.SendPropertyChanging();
					this._Mileage = value;
					this.SendPropertyChanged("Mileage");
					this.OnMileageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDefects", DbType="Bit")]
		public System.Nullable<bool> NoDefects
		{
			get
			{
				return this._NoDefects;
			}
			set
			{
				if ((this._NoDefects != value))
				{
					this.OnNoDefectsChanging(value);
					this.SendPropertyChanging();
					this._NoDefects = value;
					this.SendPropertyChanged("NoDefects");
					this.OnNoDefectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CabDoorsWindows", DbType="Bit")]
		public System.Nullable<bool> CabDoorsWindows
		{
			get
			{
				return this._CabDoorsWindows;
			}
			set
			{
				if ((this._CabDoorsWindows != value))
				{
					this.OnCabDoorsWindowsChanging(value);
					this.SendPropertyChanging();
					this._CabDoorsWindows = value;
					this.SendPropertyChanged("CabDoorsWindows");
					this.OnCabDoorsWindowsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyDoors", DbType="Bit")]
		public System.Nullable<bool> BodyDoors
		{
			get
			{
				return this._BodyDoors;
			}
			set
			{
				if ((this._BodyDoors != value))
				{
					this.OnBodyDoorsChanging(value);
					this.SendPropertyChanging();
					this._BodyDoors = value;
					this.SendPropertyChanged("BodyDoors");
					this.OnBodyDoorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilLeak", DbType="Bit")]
		public System.Nullable<bool> OilLeak
		{
			get
			{
				return this._OilLeak;
			}
			set
			{
				if ((this._OilLeak != value))
				{
					this.OnOilLeakChanging(value);
					this.SendPropertyChanging();
					this._OilLeak = value;
					this.SendPropertyChanged("OilLeak");
					this.OnOilLeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GreaseLeak", DbType="Bit")]
		public System.Nullable<bool> GreaseLeak
		{
			get
			{
				return this._GreaseLeak;
			}
			set
			{
				if ((this._GreaseLeak != value))
				{
					this.OnGreaseLeakChanging(value);
					this.SendPropertyChanging();
					this._GreaseLeak = value;
					this.SendPropertyChanged("GreaseLeak");
					this.OnGreaseLeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoolantLeak", DbType="Bit")]
		public System.Nullable<bool> CoolantLeak
		{
			get
			{
				return this._CoolantLeak;
			}
			set
			{
				if ((this._CoolantLeak != value))
				{
					this.OnCoolantLeakChanging(value);
					this.SendPropertyChanging();
					this._CoolantLeak = value;
					this.SendPropertyChanged("CoolantLeak");
					this.OnCoolantLeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuelLeak", DbType="Bit")]
		public System.Nullable<bool> FuelLeak
		{
			get
			{
				return this._FuelLeak;
			}
			set
			{
				if ((this._FuelLeak != value))
				{
					this.OnFuelLeakChanging(value);
					this.SendPropertyChanging();
					this._FuelLeak = value;
					this.SendPropertyChanged("FuelLeak");
					this.OnFuelLeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherGeneral", DbType="VarChar(20)")]
		public string OtherGeneral
		{
			get
			{
				return this._OtherGeneral;
			}
			set
			{
				if ((this._OtherGeneral != value))
				{
					this.OnOtherGeneralChanging(value);
					this.SendPropertyChanging();
					this._OtherGeneral = value;
					this.SendPropertyChanged("OtherGeneral");
					this.OnOtherGeneralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneralRemark", DbType="VarChar(40)")]
		public string GeneralRemark
		{
			get
			{
				return this._GeneralRemark;
			}
			set
			{
				if ((this._GeneralRemark != value))
				{
					this.OnGeneralRemarkChanging(value);
					this.SendPropertyChanging();
					this._GeneralRemark = value;
					this.SendPropertyChanged("GeneralRemark");
					this.OnGeneralRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OilLevel", DbType="Bit")]
		public System.Nullable<bool> OilLevel
		{
			get
			{
				return this._OilLevel;
			}
			set
			{
				if ((this._OilLevel != value))
				{
					this.OnOilLevelChanging(value);
					this.SendPropertyChanging();
					this._OilLevel = value;
					this.SendPropertyChanged("OilLevel");
					this.OnOilLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoolantLevel", DbType="Bit")]
		public System.Nullable<bool> CoolantLevel
		{
			get
			{
				return this._CoolantLevel;
			}
			set
			{
				if ((this._CoolantLevel != value))
				{
					this.OnCoolantLevelChanging(value);
					this.SendPropertyChanging();
					this._CoolantLevel = value;
					this.SendPropertyChanged("CoolantLevel");
					this.OnCoolantLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Belts", DbType="Bit")]
		public System.Nullable<bool> Belts
		{
			get
			{
				return this._Belts;
			}
			set
			{
				if ((this._Belts != value))
				{
					this.OnBeltsChanging(value);
					this.SendPropertyChanging();
					this._Belts = value;
					this.SendPropertyChanged("Belts");
					this.OnBeltsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherEngine", DbType="VarChar(20)")]
		public string OtherEngine
		{
			get
			{
				return this._OtherEngine;
			}
			set
			{
				if ((this._OtherEngine != value))
				{
					this.OnOtherEngineChanging(value);
					this.SendPropertyChanging();
					this._OtherEngine = value;
					this.SendPropertyChanged("OtherEngine");
					this.OnOtherEngineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngineRemark", DbType="VarChar(40)")]
		public string EngineRemark
		{
			get
			{
				return this._EngineRemark;
			}
			set
			{
				if ((this._EngineRemark != value))
				{
					this.OnEngineRemarkChanging(value);
					this.SendPropertyChanging();
					this._EngineRemark = value;
					this.SendPropertyChanged("EngineRemark");
					this.OnEngineRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GaugesWarning", DbType="Bit")]
		public System.Nullable<bool> GaugesWarning
		{
			get
			{
				return this._GaugesWarning;
			}
			set
			{
				if ((this._GaugesWarning != value))
				{
					this.OnGaugesWarningChanging(value);
					this.SendPropertyChanging();
					this._GaugesWarning = value;
					this.SendPropertyChanged("GaugesWarning");
					this.OnGaugesWarningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WindshieldWipers", DbType="Bit")]
		public System.Nullable<bool> WindshieldWipers
		{
			get
			{
				return this._WindshieldWipers;
			}
			set
			{
				if ((this._WindshieldWipers != value))
				{
					this.OnWindshieldWipersChanging(value);
					this.SendPropertyChanging();
					this._WindshieldWipers = value;
					this.SendPropertyChanged("WindshieldWipers");
					this.OnWindshieldWipersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horns", DbType="Bit")]
		public System.Nullable<bool> Horns
		{
			get
			{
				return this._Horns;
			}
			set
			{
				if ((this._Horns != value))
				{
					this.OnHornsChanging(value);
					this.SendPropertyChanging();
					this._Horns = value;
					this.SendPropertyChanged("Horns");
					this.OnHornsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeaterDefroster", DbType="Bit")]
		public System.Nullable<bool> HeaterDefroster
		{
			get
			{
				return this._HeaterDefroster;
			}
			set
			{
				if ((this._HeaterDefroster != value))
				{
					this.OnHeaterDefrosterChanging(value);
					this.SendPropertyChanging();
					this._HeaterDefroster = value;
					this.SendPropertyChanged("HeaterDefroster");
					this.OnHeaterDefrosterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mirrors", DbType="Bit")]
		public System.Nullable<bool> Mirrors
		{
			get
			{
				return this._Mirrors;
			}
			set
			{
				if ((this._Mirrors != value))
				{
					this.OnMirrorsChanging(value);
					this.SendPropertyChanging();
					this._Mirrors = value;
					this.SendPropertyChanged("Mirrors");
					this.OnMirrorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Steering", DbType="Bit")]
		public System.Nullable<bool> Steering
		{
			get
			{
				return this._Steering;
			}
			set
			{
				if ((this._Steering != value))
				{
					this.OnSteeringChanging(value);
					this.SendPropertyChanging();
					this._Steering = value;
					this.SendPropertyChanged("Steering");
					this.OnSteeringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clutch", DbType="Bit")]
		public System.Nullable<bool> Clutch
		{
			get
			{
				return this._Clutch;
			}
			set
			{
				if ((this._Clutch != value))
				{
					this.OnClutchChanging(value);
					this.SendPropertyChanging();
					this._Clutch = value;
					this.SendPropertyChanged("Clutch");
					this.OnClutchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceBrakes", DbType="Bit")]
		public System.Nullable<bool> ServiceBrakes
		{
			get
			{
				return this._ServiceBrakes;
			}
			set
			{
				if ((this._ServiceBrakes != value))
				{
					this.OnServiceBrakesChanging(value);
					this.SendPropertyChanging();
					this._ServiceBrakes = value;
					this.SendPropertyChanged("ServiceBrakes");
					this.OnServiceBrakesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParkingBrake", DbType="Bit")]
		public System.Nullable<bool> ParkingBrake
		{
			get
			{
				return this._ParkingBrake;
			}
			set
			{
				if ((this._ParkingBrake != value))
				{
					this.OnParkingBrakeChanging(value);
					this.SendPropertyChanging();
					this._ParkingBrake = value;
					this.SendPropertyChanged("ParkingBrake");
					this.OnParkingBrakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyBrake", DbType="Bit")]
		public System.Nullable<bool> EmergencyBrake
		{
			get
			{
				return this._EmergencyBrake;
			}
			set
			{
				if ((this._EmergencyBrake != value))
				{
					this.OnEmergencyBrakeChanging(value);
					this.SendPropertyChanging();
					this._EmergencyBrake = value;
					this.SendPropertyChanged("EmergencyBrake");
					this.OnEmergencyBrakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Triangles", DbType="Bit")]
		public System.Nullable<bool> Triangles
		{
			get
			{
				return this._Triangles;
			}
			set
			{
				if ((this._Triangles != value))
				{
					this.OnTrianglesChanging(value);
					this.SendPropertyChanging();
					this._Triangles = value;
					this.SendPropertyChanged("Triangles");
					this.OnTrianglesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FireExtinguisher", DbType="Bit")]
		public System.Nullable<bool> FireExtinguisher
		{
			get
			{
				return this._FireExtinguisher;
			}
			set
			{
				if ((this._FireExtinguisher != value))
				{
					this.OnFireExtinguisherChanging(value);
					this.SendPropertyChanging();
					this._FireExtinguisher = value;
					this.SendPropertyChanged("FireExtinguisher");
					this.OnFireExtinguisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherSafetyEquipment", DbType="Bit")]
		public System.Nullable<bool> OtherSafetyEquipment
		{
			get
			{
				return this._OtherSafetyEquipment;
			}
			set
			{
				if ((this._OtherSafetyEquipment != value))
				{
					this.OnOtherSafetyEquipmentChanging(value);
					this.SendPropertyChanging();
					this._OtherSafetyEquipment = value;
					this.SendPropertyChanged("OtherSafetyEquipment");
					this.OnOtherSafetyEquipmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpareFuses", DbType="Bit")]
		public System.Nullable<bool> SpareFuses
		{
			get
			{
				return this._SpareFuses;
			}
			set
			{
				if ((this._SpareFuses != value))
				{
					this.OnSpareFusesChanging(value);
					this.SendPropertyChanging();
					this._SpareFuses = value;
					this.SendPropertyChanged("SpareFuses");
					this.OnSpareFusesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeatBelts", DbType="Bit")]
		public System.Nullable<bool> SeatBelts
		{
			get
			{
				return this._SeatBelts;
			}
			set
			{
				if ((this._SeatBelts != value))
				{
					this.OnSeatBeltsChanging(value);
					this.SendPropertyChanging();
					this._SeatBelts = value;
					this.SendPropertyChanged("SeatBelts");
					this.OnSeatBeltsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherInCab", DbType="VarChar(20)")]
		public string OtherInCab
		{
			get
			{
				return this._OtherInCab;
			}
			set
			{
				if ((this._OtherInCab != value))
				{
					this.OnOtherInCabChanging(value);
					this.SendPropertyChanging();
					this._OtherInCab = value;
					this.SendPropertyChanged("OtherInCab");
					this.OnOtherInCabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InCabRemark", DbType="VarChar(40)")]
		public string InCabRemark
		{
			get
			{
				return this._InCabRemark;
			}
			set
			{
				if ((this._InCabRemark != value))
				{
					this.OnInCabRemarkChanging(value);
					this.SendPropertyChanging();
					this._InCabRemark = value;
					this.SendPropertyChanged("InCabRemark");
					this.OnInCabRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lights", DbType="Bit")]
		public System.Nullable<bool> Lights
		{
			get
			{
				return this._Lights;
			}
			set
			{
				if ((this._Lights != value))
				{
					this.OnLightsChanging(value);
					this.SendPropertyChanging();
					this._Lights = value;
					this.SendPropertyChanged("Lights");
					this.OnLightsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reflectors", DbType="Bit")]
		public System.Nullable<bool> Reflectors
		{
			get
			{
				return this._Reflectors;
			}
			set
			{
				if ((this._Reflectors != value))
				{
					this.OnReflectorsChanging(value);
					this.SendPropertyChanging();
					this._Reflectors = value;
					this.SendPropertyChanged("Reflectors");
					this.OnReflectorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suspension", DbType="Bit")]
		public System.Nullable<bool> Suspension
		{
			get
			{
				return this._Suspension;
			}
			set
			{
				if ((this._Suspension != value))
				{
					this.OnSuspensionChanging(value);
					this.SendPropertyChanging();
					this._Suspension = value;
					this.SendPropertyChanged("Suspension");
					this.OnSuspensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tires", DbType="Bit")]
		public System.Nullable<bool> Tires
		{
			get
			{
				return this._Tires;
			}
			set
			{
				if ((this._Tires != value))
				{
					this.OnTiresChanging(value);
					this.SendPropertyChanging();
					this._Tires = value;
					this.SendPropertyChanged("Tires");
					this.OnTiresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WheelsRimsLugs", DbType="Bit")]
		public System.Nullable<bool> WheelsRimsLugs
		{
			get
			{
				return this._WheelsRimsLugs;
			}
			set
			{
				if ((this._WheelsRimsLugs != value))
				{
					this.OnWheelsRimsLugsChanging(value);
					this.SendPropertyChanging();
					this._WheelsRimsLugs = value;
					this.SendPropertyChanged("WheelsRimsLugs");
					this.OnWheelsRimsLugsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery", DbType="Bit")]
		public System.Nullable<bool> Battery
		{
			get
			{
				return this._Battery;
			}
			set
			{
				if ((this._Battery != value))
				{
					this.OnBatteryChanging(value);
					this.SendPropertyChanging();
					this._Battery = value;
					this.SendPropertyChanged("Battery");
					this.OnBatteryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exhaust", DbType="Bit")]
		public System.Nullable<bool> Exhaust
		{
			get
			{
				return this._Exhaust;
			}
			set
			{
				if ((this._Exhaust != value))
				{
					this.OnExhaustChanging(value);
					this.SendPropertyChanging();
					this._Exhaust = value;
					this.SendPropertyChanged("Exhaust");
					this.OnExhaustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brakes", DbType="Bit")]
		public System.Nullable<bool> Brakes
		{
			get
			{
				return this._Brakes;
			}
			set
			{
				if ((this._Brakes != value))
				{
					this.OnBrakesChanging(value);
					this.SendPropertyChanging();
					this._Brakes = value;
					this.SendPropertyChanged("Brakes");
					this.OnBrakesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirLines", DbType="Bit")]
		public System.Nullable<bool> AirLines
		{
			get
			{
				return this._AirLines;
			}
			set
			{
				if ((this._AirLines != value))
				{
					this.OnAirLinesChanging(value);
					this.SendPropertyChanging();
					this._AirLines = value;
					this.SendPropertyChanged("AirLines");
					this.OnAirLinesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FifthWheel", DbType="Bit")]
		public System.Nullable<bool> FifthWheel
		{
			get
			{
				return this._FifthWheel;
			}
			set
			{
				if ((this._FifthWheel != value))
				{
					this.OnFifthWheelChanging(value);
					this.SendPropertyChanging();
					this._FifthWheel = value;
					this.SendPropertyChanged("FifthWheel");
					this.OnFifthWheelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherCoupling", DbType="Bit")]
		public System.Nullable<bool> OtherCoupling
		{
			get
			{
				return this._OtherCoupling;
			}
			set
			{
				if ((this._OtherCoupling != value))
				{
					this.OnOtherCouplingChanging(value);
					this.SendPropertyChanging();
					this._OtherCoupling = value;
					this.SendPropertyChanged("OtherCoupling");
					this.OnOtherCouplingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieDowns", DbType="Bit")]
		public System.Nullable<bool> TieDowns
		{
			get
			{
				return this._TieDowns;
			}
			set
			{
				if ((this._TieDowns != value))
				{
					this.OnTieDownsChanging(value);
					this.SendPropertyChanging();
					this._TieDowns = value;
					this.SendPropertyChanged("TieDowns");
					this.OnTieDownsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherExterior", DbType="VarChar(20)")]
		public string OtherExterior
		{
			get
			{
				return this._OtherExterior;
			}
			set
			{
				if ((this._OtherExterior != value))
				{
					this.OnOtherExteriorChanging(value);
					this.SendPropertyChanging();
					this._OtherExterior = value;
					this.SendPropertyChanged("OtherExterior");
					this.OnOtherExteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExteriorRemark", DbType="VarChar(40)")]
		public string ExteriorRemark
		{
			get
			{
				return this._ExteriorRemark;
			}
			set
			{
				if ((this._ExteriorRemark != value))
				{
					this.OnExteriorRemarkChanging(value);
					this.SendPropertyChanging();
					this._ExteriorRemark = value;
					this.SendPropertyChanged("ExteriorRemark");
					this.OnExteriorRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDateTime
		{
			get
			{
				return this._CreatedDateTime;
			}
			set
			{
				if ((this._CreatedDateTime != value))
				{
					this.OnCreatedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreatedDateTime = value;
					this.SendPropertyChanged("CreatedDateTime");
					this.OnCreatedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertifyRepairsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CertifyRepairsDate
		{
			get
			{
				return this._CertifyRepairsDate;
			}
			set
			{
				if ((this._CertifyRepairsDate != value))
				{
					this.OnCertifyRepairsDateChanging(value);
					this.SendPropertyChanging();
					this._CertifyRepairsDate = value;
					this.SendPropertyChanged("CertifyRepairsDate");
					this.OnCertifyRepairsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepairsMadeFlag", DbType="Bit")]
		public System.Nullable<bool> RepairsMadeFlag
		{
			get
			{
				return this._RepairsMadeFlag;
			}
			set
			{
				if ((this._RepairsMadeFlag != value))
				{
					this.OnRepairsMadeFlagChanging(value);
					this.SendPropertyChanging();
					this._RepairsMadeFlag = value;
					this.SendPropertyChanged("RepairsMadeFlag");
					this.OnRepairsMadeFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RONumber", DbType="VarChar(20)")]
		public string RONumber
		{
			get
			{
				return this._RONumber;
			}
			set
			{
				if ((this._RONumber != value))
				{
					this.OnRONumberChanging(value);
					this.SendPropertyChanging();
					this._RONumber = value;
					this.SendPropertyChanged("RONumber");
					this.OnRONumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertifiedBy", DbType="VarChar(30)")]
		public string CertifiedBy
		{
			get
			{
				return this._CertifiedBy;
			}
			set
			{
				if ((this._CertifiedBy != value))
				{
					this.OnCertifiedByChanging(value);
					this.SendPropertyChanging();
					this._CertifiedBy = value;
					this.SendPropertyChanged("CertifiedBy");
					this.OnCertifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertifiedLocation", DbType="VarChar(30)")]
		public string CertifiedLocation
		{
			get
			{
				return this._CertifiedLocation;
			}
			set
			{
				if ((this._CertifiedLocation != value))
				{
					this.OnCertifiedLocationChanging(value);
					this.SendPropertyChanging();
					this._CertifiedLocation = value;
					this.SendPropertyChanged("CertifiedLocation");
					this.OnCertifiedLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewingDriverDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReviewingDriverDate
		{
			get
			{
				return this._ReviewingDriverDate;
			}
			set
			{
				if ((this._ReviewingDriverDate != value))
				{
					this.OnReviewingDriverDateChanging(value);
					this.SendPropertyChanging();
					this._ReviewingDriverDate = value;
					this.SendPropertyChanged("ReviewingDriverDate");
					this.OnReviewingDriverDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewingDriverName", DbType="VarChar(30)")]
		public string ReviewingDriverName
		{
			get
			{
				return this._ReviewingDriverName;
			}
			set
			{
				if ((this._ReviewingDriverName != value))
				{
					this.OnReviewingDriverNameChanging(value);
					this.SendPropertyChanging();
					this._ReviewingDriverName = value;
					this.SendPropertyChanged("ReviewingDriverName");
					this.OnReviewingDriverNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewingDriverNumber", DbType="VarChar(10)")]
		public string ReviewingDriverNumber
		{
			get
			{
				return this._ReviewingDriverNumber;
			}
			set
			{
				if ((this._ReviewingDriverNumber != value))
				{
					this.OnReviewingDriverNumberChanging(value);
					this.SendPropertyChanging();
					this._ReviewingDriverNumber = value;
					this.SendPropertyChanged("ReviewingDriverNumber");
					this.OnReviewingDriverNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVIRTowed")]
	public partial class DVIRTowed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DVIRTowedId;
		
		private System.Nullable<int> _DriverNo;
		
		private string _TrailerChassis;
		
		private string _Location;
		
		private string _Mileage;
		
		private string _Remark1;
		
		private string _Remark2;
		
		private System.Nullable<bool> _NoDefects;
		
		private System.Nullable<bool> _BodyDoors;
		
		private System.Nullable<bool> _TieDowns;
		
		private System.Nullable<bool> _Lights;
		
		private System.Nullable<bool> _Reflectors;
		
		private System.Nullable<bool> _Suspension;
		
		private System.Nullable<bool> _Tires;
		
		private System.Nullable<bool> _WheelsRimsLugs;
		
		private System.Nullable<bool> _Brakes;
		
		private System.Nullable<bool> _LandingGear;
		
		private System.Nullable<bool> _KingpinUpperPlate;
		
		private System.Nullable<bool> _FifthWheelDolly;
		
		private System.Nullable<bool> _OtherCoupling;
		
		private System.Nullable<bool> _RearEndProtection;
		
		private string _Other;
		
		private System.Nullable<System.DateTime> _CreatedDateTime;
		
		private System.Nullable<System.DateTime> _CertifyRepairsDate;
		
		private System.Nullable<bool> _RepairsMadeFlag;
		
		private string _RONumber;
		
		private string _CertifiedBy;
		
		private string _CertifiedLocation;
		
		private System.Nullable<System.DateTime> _ReviewingDriverDate;
		
		private string _ReviewingDriverName;
		
		private string _ReviewingDriverNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDVIRTowedIdChanging(int value);
    partial void OnDVIRTowedIdChanged();
    partial void OnDriverNoChanging(System.Nullable<int> value);
    partial void OnDriverNoChanged();
    partial void OnTrailerChassisChanging(string value);
    partial void OnTrailerChassisChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnMileageChanging(string value);
    partial void OnMileageChanged();
    partial void OnRemark1Changing(string value);
    partial void OnRemark1Changed();
    partial void OnRemark2Changing(string value);
    partial void OnRemark2Changed();
    partial void OnNoDefectsChanging(System.Nullable<bool> value);
    partial void OnNoDefectsChanged();
    partial void OnBodyDoorsChanging(System.Nullable<bool> value);
    partial void OnBodyDoorsChanged();
    partial void OnTieDownsChanging(System.Nullable<bool> value);
    partial void OnTieDownsChanged();
    partial void OnLightsChanging(System.Nullable<bool> value);
    partial void OnLightsChanged();
    partial void OnReflectorsChanging(System.Nullable<bool> value);
    partial void OnReflectorsChanged();
    partial void OnSuspensionChanging(System.Nullable<bool> value);
    partial void OnSuspensionChanged();
    partial void OnTiresChanging(System.Nullable<bool> value);
    partial void OnTiresChanged();
    partial void OnWheelsRimsLugsChanging(System.Nullable<bool> value);
    partial void OnWheelsRimsLugsChanged();
    partial void OnBrakesChanging(System.Nullable<bool> value);
    partial void OnBrakesChanged();
    partial void OnLandingGearChanging(System.Nullable<bool> value);
    partial void OnLandingGearChanged();
    partial void OnKingpinUpperPlateChanging(System.Nullable<bool> value);
    partial void OnKingpinUpperPlateChanged();
    partial void OnFifthWheelDollyChanging(System.Nullable<bool> value);
    partial void OnFifthWheelDollyChanged();
    partial void OnOtherCouplingChanging(System.Nullable<bool> value);
    partial void OnOtherCouplingChanged();
    partial void OnRearEndProtectionChanging(System.Nullable<bool> value);
    partial void OnRearEndProtectionChanged();
    partial void OnOtherChanging(string value);
    partial void OnOtherChanged();
    partial void OnCreatedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateTimeChanged();
    partial void OnCertifyRepairsDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCertifyRepairsDateChanged();
    partial void OnRepairsMadeFlagChanging(System.Nullable<bool> value);
    partial void OnRepairsMadeFlagChanged();
    partial void OnRONumberChanging(string value);
    partial void OnRONumberChanged();
    partial void OnCertifiedByChanging(string value);
    partial void OnCertifiedByChanged();
    partial void OnCertifiedLocationChanging(string value);
    partial void OnCertifiedLocationChanged();
    partial void OnReviewingDriverDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReviewingDriverDateChanged();
    partial void OnReviewingDriverNameChanging(string value);
    partial void OnReviewingDriverNameChanged();
    partial void OnReviewingDriverNumberChanging(string value);
    partial void OnReviewingDriverNumberChanged();
    #endregion
		
		public DVIRTowed()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVIRTowedId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DVIRTowedId
		{
			get
			{
				return this._DVIRTowedId;
			}
			set
			{
				if ((this._DVIRTowedId != value))
				{
					this.OnDVIRTowedIdChanging(value);
					this.SendPropertyChanging();
					this._DVIRTowedId = value;
					this.SendPropertyChanged("DVIRTowedId");
					this.OnDVIRTowedIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriverNo", DbType="Int")]
		public System.Nullable<int> DriverNo
		{
			get
			{
				return this._DriverNo;
			}
			set
			{
				if ((this._DriverNo != value))
				{
					this.OnDriverNoChanging(value);
					this.SendPropertyChanging();
					this._DriverNo = value;
					this.SendPropertyChanged("DriverNo");
					this.OnDriverNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrailerChassis", DbType="VarChar(11)")]
		public string TrailerChassis
		{
			get
			{
				return this._TrailerChassis;
			}
			set
			{
				if ((this._TrailerChassis != value))
				{
					this.OnTrailerChassisChanging(value);
					this.SendPropertyChanging();
					this._TrailerChassis = value;
					this.SendPropertyChanged("TrailerChassis");
					this.OnTrailerChassisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(20)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mileage", DbType="VarChar(20)")]
		public string Mileage
		{
			get
			{
				return this._Mileage;
			}
			set
			{
				if ((this._Mileage != value))
				{
					this.OnMileageChanging(value);
					this.SendPropertyChanging();
					this._Mileage = value;
					this.SendPropertyChanged("Mileage");
					this.OnMileageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark1", DbType="VarChar(40)")]
		public string Remark1
		{
			get
			{
				return this._Remark1;
			}
			set
			{
				if ((this._Remark1 != value))
				{
					this.OnRemark1Changing(value);
					this.SendPropertyChanging();
					this._Remark1 = value;
					this.SendPropertyChanged("Remark1");
					this.OnRemark1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark2", DbType="VarChar(40)")]
		public string Remark2
		{
			get
			{
				return this._Remark2;
			}
			set
			{
				if ((this._Remark2 != value))
				{
					this.OnRemark2Changing(value);
					this.SendPropertyChanging();
					this._Remark2 = value;
					this.SendPropertyChanged("Remark2");
					this.OnRemark2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDefects", DbType="Bit")]
		public System.Nullable<bool> NoDefects
		{
			get
			{
				return this._NoDefects;
			}
			set
			{
				if ((this._NoDefects != value))
				{
					this.OnNoDefectsChanging(value);
					this.SendPropertyChanging();
					this._NoDefects = value;
					this.SendPropertyChanged("NoDefects");
					this.OnNoDefectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyDoors", DbType="Bit")]
		public System.Nullable<bool> BodyDoors
		{
			get
			{
				return this._BodyDoors;
			}
			set
			{
				if ((this._BodyDoors != value))
				{
					this.OnBodyDoorsChanging(value);
					this.SendPropertyChanging();
					this._BodyDoors = value;
					this.SendPropertyChanged("BodyDoors");
					this.OnBodyDoorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieDowns", DbType="Bit")]
		public System.Nullable<bool> TieDowns
		{
			get
			{
				return this._TieDowns;
			}
			set
			{
				if ((this._TieDowns != value))
				{
					this.OnTieDownsChanging(value);
					this.SendPropertyChanging();
					this._TieDowns = value;
					this.SendPropertyChanged("TieDowns");
					this.OnTieDownsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lights", DbType="Bit")]
		public System.Nullable<bool> Lights
		{
			get
			{
				return this._Lights;
			}
			set
			{
				if ((this._Lights != value))
				{
					this.OnLightsChanging(value);
					this.SendPropertyChanging();
					this._Lights = value;
					this.SendPropertyChanged("Lights");
					this.OnLightsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reflectors", DbType="Bit")]
		public System.Nullable<bool> Reflectors
		{
			get
			{
				return this._Reflectors;
			}
			set
			{
				if ((this._Reflectors != value))
				{
					this.OnReflectorsChanging(value);
					this.SendPropertyChanging();
					this._Reflectors = value;
					this.SendPropertyChanged("Reflectors");
					this.OnReflectorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suspension", DbType="Bit")]
		public System.Nullable<bool> Suspension
		{
			get
			{
				return this._Suspension;
			}
			set
			{
				if ((this._Suspension != value))
				{
					this.OnSuspensionChanging(value);
					this.SendPropertyChanging();
					this._Suspension = value;
					this.SendPropertyChanged("Suspension");
					this.OnSuspensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tires", DbType="Bit")]
		public System.Nullable<bool> Tires
		{
			get
			{
				return this._Tires;
			}
			set
			{
				if ((this._Tires != value))
				{
					this.OnTiresChanging(value);
					this.SendPropertyChanging();
					this._Tires = value;
					this.SendPropertyChanged("Tires");
					this.OnTiresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WheelsRimsLugs", DbType="Bit")]
		public System.Nullable<bool> WheelsRimsLugs
		{
			get
			{
				return this._WheelsRimsLugs;
			}
			set
			{
				if ((this._WheelsRimsLugs != value))
				{
					this.OnWheelsRimsLugsChanging(value);
					this.SendPropertyChanging();
					this._WheelsRimsLugs = value;
					this.SendPropertyChanged("WheelsRimsLugs");
					this.OnWheelsRimsLugsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brakes", DbType="Bit")]
		public System.Nullable<bool> Brakes
		{
			get
			{
				return this._Brakes;
			}
			set
			{
				if ((this._Brakes != value))
				{
					this.OnBrakesChanging(value);
					this.SendPropertyChanging();
					this._Brakes = value;
					this.SendPropertyChanged("Brakes");
					this.OnBrakesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandingGear", DbType="Bit")]
		public System.Nullable<bool> LandingGear
		{
			get
			{
				return this._LandingGear;
			}
			set
			{
				if ((this._LandingGear != value))
				{
					this.OnLandingGearChanging(value);
					this.SendPropertyChanging();
					this._LandingGear = value;
					this.SendPropertyChanged("LandingGear");
					this.OnLandingGearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KingpinUpperPlate", DbType="Bit")]
		public System.Nullable<bool> KingpinUpperPlate
		{
			get
			{
				return this._KingpinUpperPlate;
			}
			set
			{
				if ((this._KingpinUpperPlate != value))
				{
					this.OnKingpinUpperPlateChanging(value);
					this.SendPropertyChanging();
					this._KingpinUpperPlate = value;
					this.SendPropertyChanged("KingpinUpperPlate");
					this.OnKingpinUpperPlateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FifthWheelDolly", DbType="Bit")]
		public System.Nullable<bool> FifthWheelDolly
		{
			get
			{
				return this._FifthWheelDolly;
			}
			set
			{
				if ((this._FifthWheelDolly != value))
				{
					this.OnFifthWheelDollyChanging(value);
					this.SendPropertyChanging();
					this._FifthWheelDolly = value;
					this.SendPropertyChanged("FifthWheelDolly");
					this.OnFifthWheelDollyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherCoupling", DbType="Bit")]
		public System.Nullable<bool> OtherCoupling
		{
			get
			{
				return this._OtherCoupling;
			}
			set
			{
				if ((this._OtherCoupling != value))
				{
					this.OnOtherCouplingChanging(value);
					this.SendPropertyChanging();
					this._OtherCoupling = value;
					this.SendPropertyChanged("OtherCoupling");
					this.OnOtherCouplingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RearEndProtection", DbType="Bit")]
		public System.Nullable<bool> RearEndProtection
		{
			get
			{
				return this._RearEndProtection;
			}
			set
			{
				if ((this._RearEndProtection != value))
				{
					this.OnRearEndProtectionChanging(value);
					this.SendPropertyChanging();
					this._RearEndProtection = value;
					this.SendPropertyChanged("RearEndProtection");
					this.OnRearEndProtectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="VarChar(20)")]
		public string Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this.OnOtherChanging(value);
					this.SendPropertyChanging();
					this._Other = value;
					this.SendPropertyChanged("Other");
					this.OnOtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDateTime
		{
			get
			{
				return this._CreatedDateTime;
			}
			set
			{
				if ((this._CreatedDateTime != value))
				{
					this.OnCreatedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreatedDateTime = value;
					this.SendPropertyChanged("CreatedDateTime");
					this.OnCreatedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertifyRepairsDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CertifyRepairsDate
		{
			get
			{
				return this._CertifyRepairsDate;
			}
			set
			{
				if ((this._CertifyRepairsDate != value))
				{
					this.OnCertifyRepairsDateChanging(value);
					this.SendPropertyChanging();
					this._CertifyRepairsDate = value;
					this.SendPropertyChanged("CertifyRepairsDate");
					this.OnCertifyRepairsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepairsMadeFlag", DbType="Bit")]
		public System.Nullable<bool> RepairsMadeFlag
		{
			get
			{
				return this._RepairsMadeFlag;
			}
			set
			{
				if ((this._RepairsMadeFlag != value))
				{
					this.OnRepairsMadeFlagChanging(value);
					this.SendPropertyChanging();
					this._RepairsMadeFlag = value;
					this.SendPropertyChanged("RepairsMadeFlag");
					this.OnRepairsMadeFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RONumber", DbType="VarChar(20)")]
		public string RONumber
		{
			get
			{
				return this._RONumber;
			}
			set
			{
				if ((this._RONumber != value))
				{
					this.OnRONumberChanging(value);
					this.SendPropertyChanging();
					this._RONumber = value;
					this.SendPropertyChanged("RONumber");
					this.OnRONumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertifiedBy", DbType="VarChar(30)")]
		public string CertifiedBy
		{
			get
			{
				return this._CertifiedBy;
			}
			set
			{
				if ((this._CertifiedBy != value))
				{
					this.OnCertifiedByChanging(value);
					this.SendPropertyChanging();
					this._CertifiedBy = value;
					this.SendPropertyChanged("CertifiedBy");
					this.OnCertifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertifiedLocation", DbType="VarChar(30)")]
		public string CertifiedLocation
		{
			get
			{
				return this._CertifiedLocation;
			}
			set
			{
				if ((this._CertifiedLocation != value))
				{
					this.OnCertifiedLocationChanging(value);
					this.SendPropertyChanging();
					this._CertifiedLocation = value;
					this.SendPropertyChanged("CertifiedLocation");
					this.OnCertifiedLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewingDriverDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReviewingDriverDate
		{
			get
			{
				return this._ReviewingDriverDate;
			}
			set
			{
				if ((this._ReviewingDriverDate != value))
				{
					this.OnReviewingDriverDateChanging(value);
					this.SendPropertyChanging();
					this._ReviewingDriverDate = value;
					this.SendPropertyChanged("ReviewingDriverDate");
					this.OnReviewingDriverDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewingDriverName", DbType="VarChar(30)")]
		public string ReviewingDriverName
		{
			get
			{
				return this._ReviewingDriverName;
			}
			set
			{
				if ((this._ReviewingDriverName != value))
				{
					this.OnReviewingDriverNameChanging(value);
					this.SendPropertyChanging();
					this._ReviewingDriverName = value;
					this.SendPropertyChanged("ReviewingDriverName");
					this.OnReviewingDriverNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewingDriverNumber", DbType="VarChar(10)")]
		public string ReviewingDriverNumber
		{
			get
			{
				return this._ReviewingDriverNumber;
			}
			set
			{
				if ((this._ReviewingDriverNumber != value))
				{
					this.OnReviewingDriverNumberChanging(value);
					this.SendPropertyChanging();
					this._ReviewingDriverNumber = value;
					this.SendPropertyChanged("ReviewingDriverNumber");
					this.OnReviewingDriverNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
